version: '2.3'

services:
  user-postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: ./user/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432
    env_file: ./product/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: ./user/Dockerfile
    env_file: ./user/.env
    ports:
      - "50051:50051"
    volumes:
      - ./js-commons:/js-commons
      - /js-commons/node_modules
      - ./user:/user-service
      - /user-service/node_modules
    depends_on:
      user-postgres:
        condition: service_healthy
    links:
      - user-postgres

  js-commons:
    build:
      context: .
      dockerfile: ./js-commons/Dockerfile
    volumes:
      - ./js-commons:/js-commons
      - /js-commons/node_modules

  user-migrate-up:
    extends: js-commons
    env_file: ./user/.env
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/sequelize.js --migrations-path /user/src/ports/sequelize/migrations/
    volumes:
      - ./user:/user
    depends_on:
      user-postgres:
        condition: service_healthy

  user-migrate-down:
    extends: js-commons
    env_file: ./user/.env
    entrypoint: node_modules/.bin/sequelize db:migrate:undo --config src/config/sequelize.js --migrations-path /user/src/ports/sequelize/migrations/
    volumes:
      - ./user:/user
    depends_on:
      user-postgres:
        condition: service_healthy

  user-seed-generate:
    extends: js-commons
    env_file: ./user/.env
    entrypoint: node_modules/.bin/sequelize db:seed:all --config src/config/sequelize.js --seeders-path /user/src/ports/sequelize/seeders/
    volumes:
      - ./user:/user
    depends_on:
      user-postgres:
        condition: service_healthy

  user-seed-destroy:
    extends: js-commons
    env_file: ./user/.env
    entrypoint: node_modules/.bin/sequelize db:seed:undo --config src/config/sequelize.js --seeders-path /user/src/ports/sequelize/seeders/
    volumes:
      - ./user:/user
    depends_on:
      user-postgres:
        condition: service_healthy

  product-service:
    build:
      context: .
      dockerfile: ./product/Dockerfile
    env_file: ./product/.env
    ports:
      - "3000:3000"
    volumes:
      - ./js-commons:/js-commons
      - /js-commons/node_modules
      - ./product:/product-service
      - /product-service/node_modules
    depends_on:
      product-postgres:
        condition: service_healthy
    links:
      - product-postgres
      - discount-service

  product-migrate-up:
    extends: js-commons
    env_file: ./product/.env
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/config/sequelize.js --migrations-path /product/src/ports/sequelize/migrations/
    volumes:
      - ./product:/product
    depends_on:
      product-postgres:
        condition: service_healthy

  product-migrate-down:
    extends: js-commons
    env_file: ./product/.env
    entrypoint: node_modules/.bin/sequelize db:migrate:undo --config src/config/sequelize.js --migrations-path /product/src/ports/sequelize/migrations/
    volumes:
      - ./product:/product
    depends_on:
      product-postgres:
        condition: service_healthy

  product-seed-generate:
    extends: js-commons
    env_file: ./product/.env
    entrypoint: node_modules/.bin/sequelize db:seed:all --config src/config/sequelize.js --seeders-path /product/src/ports/sequelize/seeders/
    volumes:
      - ./product:/product
    depends_on:
      product-postgres:
        condition: service_healthy

  product-seed-destroy:
    extends: js-commons
    env_file: ./product/.env
    entrypoint: node_modules/.bin/sequelize db:seed:undo --config src/config/sequelize.js --seeders-path /product/src/ports/sequelize/seeders/
    volumes:
      - ./product:/product
    depends_on:
      product-postgres:
        condition: service_healthy

  discount-service:
    build:
      context: .
      dockerfile: ./discount/Dockerfile
    volumes:
      - ./discount:/discount-service
      - /discount-service/target
    ports:
      - "4000:4000"
    links:
      - user-service
